apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - bootstrap-namespaces.yaml
  - ../../apps/imagepullsecret-patcher/
  - ../../apps/threatstack/
  - ../../apps/fluent-bit/
  - ../../apps/prometheus-adapter/
