apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

  # Apps enabled for this cluster
  - ../../apps/metallb/overlays/rpi-1

  # Monitoring
  - ../../../apps/prometheus/overlays/rpi-1
