apiVersion: v2
name: grafana
description: A Helm Chart for Grafana
type: application
version: 0.1.0

dependencies:
- name: grafana
  version: 6.29.5
  repository: https://grafana.github.io/helm-charts
