apiVersion: v2
name: prometheus
description: A Helm Chart for Prometheus
type: application
version: 0.1.0

dependencies:
- name: prometheus
  version: 15.9.0
  repository: https://prometheus-community.github.io/helm-charts
