apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    path: apps/prometheus
    repoURL: https://github.com/rfdez/raspberrypi-kubernetes
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  project: default
  ignoreDifferences:
    - kind: Serviceaccount
      jsonPointers:
      - /imagePullSecrets
