apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

    # Apps enabled for this cluster
  - ../../../apps/n8n/overlays/oke-1

  # Monitoring
  - ../../../apps/prometheus/overlays/oke-1
  - ../../../apps/grafana/overlays/oke-1
